"""empty message

Revision ID: 24ee40e158e
Revises: 592eca9c956
Create Date: 2014-10-16 15:25:36.409508

"""

# revision identifiers, used by Alembic.
revision = '24ee40e158e'
down_revision = '592eca9c956'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
