"""empty message

Revision ID: 29acc9778c6
Revises: 6fca829ee4
Create Date: 2014-10-21 15:27:48.413267

"""

# revision identifiers, used by Alembic.
revision = '29acc9778c6'
down_revision = '6fca829ee4'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
