"""empty message

Revision ID: 3be27d3903
Revises: 59bcc9a0fab
Create Date: 2014-12-02 14:33:22.748523

"""

# revision identifiers, used by Alembic.
revision = '3be27d3903'
down_revision = '59bcc9a0fab'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pictures', sa.Column('filename', sa.String(length=80), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pictures', 'filename')
    ### end Alembic commands ###
