"""empty message

Revision ID: 592eca9c956
Revises: 34dd7135840
Create Date: 2014-10-15 18:44:35.250736

"""

# revision identifiers, used by Alembic.
revision = '592eca9c956'
down_revision = '34dd7135840'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('posts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=80), nullable=True),
    sa.Column('subtitle', sa.String(length=80), nullable=True),
    sa.Column('body', sa.Text(), nullable=True),
    sa.Column('date', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('title')
    )
    op.create_table('user_posts',
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('post_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['post_id'], ['posts.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], )
    )
    op.drop_table('sum_results')
    op.drop_table('table_users')
    op.drop_table('tables')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('table_users',
    sa.Column('id', sa.INTEGER(), server_default="nextval('table_users_id_seq'::regclass)", nullable=False),
    sa.Column('table_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('write', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['table_id'], ['tables.id'], name='table_users_table_id_fkey'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='table_users_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='table_users_pkey')
    )
    op.create_table('tables',
    sa.Column('id', sa.INTEGER(), server_default="nextval('tables_id_seq'::regclass)", nullable=False),
    sa.Column('table_name', sa.VARCHAR(length=80), autoincrement=False, nullable=True),
    sa.Column('creator', sa.VARCHAR(length=80), autoincrement=False, nullable=True),
    sa.Column('owner', sa.VARCHAR(length=80), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='tables_pkey')
    )
    op.create_table('sum_results',
    sa.Column('id', sa.INTEGER(), server_default="nextval('sum_results_id_seq'::regclass)", nullable=False),
    sa.Column('sum', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='sum_results_pkey')
    )
    op.drop_table('user_posts')
    op.drop_table('posts')
    ### end Alembic commands ###
