"""empty message

Revision ID: 59bcc9a0fab
Revises: 27da8b51b0
Create Date: 2014-11-20 13:21:22.394277

"""

# revision identifiers, used by Alembic.
revision = '59bcc9a0fab'
down_revision = '27da8b51b0'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pictures',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('post_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['post_id'], ['posts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('posts', sa.Column('posted_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('posts', sa.Column('user_id', sa.Integer(), nullable=True))
    op.drop_column('posts', 'author')
    op.drop_column('posts', 'date')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('date', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.add_column('posts', sa.Column('author', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('posts', 'user_id')
    op.drop_column('posts', 'posted_at')
    op.drop_table('pictures')
    ### end Alembic commands ###
