"""empty message

Revision ID: 6fca829ee4
Revises: 24ee40e158e
Create Date: 2014-10-21 15:24:09.773371

"""

# revision identifiers, used by Alembic.
revision = '6fca829ee4'
down_revision = '24ee40e158e'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('author', sa.Integer(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('posts', 'author')
    ### end Alembic commands ###
