"""empty message

Revision ID: d11a06cb80
Revises: 29acc9778c6
Create Date: 2014-10-21 22:04:22.355134

"""

# revision identifiers, used by Alembic.
revision = 'd11a06cb80'
down_revision = '29acc9778c6'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_posts')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_posts',
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('post_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['post_id'], ['posts.id'], name='user_posts_post_id_fkey'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='user_posts_user_id_fkey')
    )
    ### end Alembic commands ###
